services:
  database:
    container_name: ${CONTAINER_PREFIX}_database
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

  redis:
    container_name: ${CONTAINER_PREFIX}_redis
    image: redis:latest
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

  php:
    container_name: ${CONTAINER_PREFIX}_php
    build: ./infra/php
    restart: always
    volumes:
      - ./src:/var/www/html
    links:
      - database
      - redis

  web:
    container_name: ${CONTAINER_PREFIX}_nginx
    image: nginx:latest
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/nginx/ssl:/etc/nginx/ssl
      - ./src:/var/www/html
    ports:
      - "9000:9000"
      - "443:443"
    links:
      - php

volumes:
  database_data:
  redis_data:
